### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zaqq357** [dluvizon/harskel#1]
Dear author, how to solve this bug？
wrong usage ./ 
The matrix dimension must be consistent.

Error normc (line 2)
X = x. / (Sum (abs (x). ^ 2). ^ 0.5);

Thank you.

**Comment by dluvizon** [comment]
Hi @zaqq357 ,

Which version of Matlab are you using?
I was not able to reproduce the bug on version R2016b.

Considering the normal behaviour, `x` is expected to be a matrix MxN, `sum()` should return a matrix 1xN, and the `rdivide (./)` will divide each column from `x` by the corresponding scalar returned by `sum()`.

**Comment by zaqq357** [comment]
Hi @dluvizon 
The version of Matlab is R2014a.
As you said, x is a matrix MxN, sum() should return a matrix 1xN. But the help for rdivide (./) said: c = rdivide(a,b) and c = a./b perform right-array division by dividing each element of a by the corresponding element of b. If inputs a and b are not the same size, one of them must be a scalar value.
So x and the result returned by sum() are not the same size, and why did you say the result returned by sum() is a scalar? Does not the scalar means a matrix 1x1?

**Comment by dluvizon** [comment]
You are right, my function is not very canonical according to the Matlab documentation.

However, in my version of Matlab, it behaves like a said (I edited my last comment replacing **line** by **column**): if `a` is a matrix MxN and `b` is a vector 1xN, the operation `a ./ b` divides every column of `a` by the corresponding scalar on `b`, since there are N columns in `a` and N scalars in `b`.

It seems strange to me if this operation (rdivide) works not the same way on different versions of Matlab.

Anyway, if you have the Neural Network Toolbox, you can use the build-in function `normc`.

**Comment by zaqq357** [comment]
Thank you very much. The problem has been solved after I changed the version of Matlab.
